<?php
//	ini_set("display_errors","1");
//	ERROR_REPORTING(E_ALL);


if ($_GET['page'] == '') {
  $_GET['page'] = 'index.htm';
}
$hash_frag = $_GET['_escaped_fragment_'];
if (isset ($hash_frag)) {
  if ($hash_frag == '') {
    $_GET['page'] = 'index.htm';
  } else {
    $parts = explode ('=', $hash_frag);
    $key = $parts[0];
    $value = $parts[1];
    if ($key == 'wiki') {
      $_GET['page'] = $value.".htm";
    } else if ($key == 'api') {
      $_GET['page'] = $value.".html";
    } else {
      $_GET['page'] = 'index.htm';
    }
  }
}

function get_title () {
  $is_wiki = substr($_GET['page'], -4) === '.htm';
  $segments = explode ('/', $_GET['page']);

  for ($i = 0; $i < count ($segments) ; $i++) {
    $segments[$i] = htmlentities ($segments[$i]);
  }

  if (count ($segments) == 2) {
    // package content
    if ($is_wiki) {
      return $segments[0];
    } else {
      // api description: <element-name> -- <package-name>
      return basename ($segments[1], ".html") . ' &ndash; ' . $segments[0];
    }
  }

  return  "Valadoc.org - Stays crunchy. Even in milk.";
}

?>
<html>
	<head>
		<title><?php echo get_title (); ?></title>
		<meta name="fragment" content="!">
		<script type="text/javascript" src="/jquery.min.js"></script>
		<script type="text/javascript" src="/jquery.ba-hashchange.min.js"></script>
		<script type="text/javascript" src="/jquery.spinner.js"></script>
		<script type="text/javascript" src="/wtooltip.js"></script>
		<script type="text/javascript" src="/valadoc.js"></script>
		<link href="/style.css" rel="stylesheet" type="text/css">
		<link rel="apple-touch-icon" href="devhelp.png" />
	</head>
	<body>
	  <table border="0" cellspacing="0" cellpadding="0" width="100%">
	    <tr>
	      <td width="240" valign="top">
		<div id="navigation">
		<div id="search-box">
		  <input id="search-field" type="text" placeholder="Search" autofocus="autofocus" autocompletion="off" autosave="search" /><img id="search-field-clear" src="/clean.svg" />
		</div>
		<ul id="search-results"></ul>
		<div id="navigation-content">
		  <noscript>
		    <?php @readfile ($_GET['page'] . '.navi.tpl'); ?>
		  </noscript>
		</div>
	      </td>

	      <td width="100%" valign="top">
		<div id="content-wrapper">
		<div id="header">
		  <div id="topbar"><div class="space"></div>
		    <div id="stayscrunchy">Stays crunchy ...</div>
		    <div id="eveninmilk">... even in milk.</div>
		    <ul>
		      <li><a href="http://live.gnome.org/Valadoc">Valadoc</a></li>
		      <li><a href="http://live.gnome.org/Vala">Vala</a></li>
		      <li><a href="https://live.gnome.org/Vala/Documentation">Tutorial</a></li>
		      <li><a href="http://valajournal.blogspot.com/">Vala Journal</a></li>
		      <li><a href="/index.htm">API-References</a></li>
		      <li><a href="/markup.htm">Markup</a></li>
		      <li><a href="/about.htm">About</a></li>
		    </ul>
		  </div>
		  <div class="space"></div>
		</div>
		<div>
		  <div id="content">
		    <noscript>
		      <?php @readfile ($_GET['page'] . '.content.tpl'); ?>
		    </noscript>
		  </div>
		  <div id="comments" style="margin: 10px;" />
		  <div class="site_footer">
		    <!-- Generated by <a href="http://www.valadoc.org/">Valadoc</a> -->
		  </div>
		</div>
	      </td>
	    </tr>
	  </table>
  
	  <script type="text/javascript">
	    //if (document.location.hash != '') {
	    load_link (hash_to_url (window.location.hash), window.location.hostname);
	    //}
	  </script>
	</body>
</html>
